In [1]:
# Python program to create 
# Image Classifier using CNN 
  
# Importing the required libraries 
import cv2 
import os 
import numpy as np 
from random import shuffle 
from tqdm import tqdm 

# Image database to Array Database

## Loop to transform the database of all images to arrays database

In [2]:
import os
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import img_to_array

# Path for looking all jpg files
path = './Images/'

# All path files for jpg files contained in the files list
files = []
# r=root, d=directories, f = files
for r, d, f in os.walk(path):
    for file in f:
        if '.jpg' in file:
            if 'gif' not in file:
                if 'bar_0527.jpg' not in file:
                    files.append(os.path.join(r, file))

# Use it for testing the code. It limits the files to 10 files
# files = files[0:10]

# Convert all images in a Database
data = []
X = []
y = []
for f in files:
    print(f)
    # Import the Image
    filepath = f
    image_size = 50
    LR = 1e-3
    # img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE) 
    img = cv2.imread(filepath, 0) 
    img = cv2.resize(img, (image_size, image_size))
    X.append(img)
    # Extract the folder name from each path
    # Get the directory name from the specified path 
    dirname = os.path.dirname(filepath)
    # Replace the initial part of the folder to leave just the folder name
    dirname = dirname.replace("./Images/", "")
    y.append(dirname)
    # data.append([np.array(X),np.array(y)])

# suffle(data)

jpg
./Images/subway/subway_0351.jpg
./Images/subway/subway_0437.jpg
./Images/subway/subway_0386.jpg
./Images/subway/subway_0392.jpg
./Images/subway/subway_0393.jpg
./Images/subway/subway_0387.jpg
./Images/subway/subway_0350.jpg
./Images/subway/subway_0436.jpg
./Images/subway/subway_0422.jpg
./Images/subway/subway_0344.jpg
./Images/subway/subway_0378.jpg
./Images/subway/subway_0191.jpg
./Images/subway/subway_0185.jpg
./Images/subway/metropolitana_50_18_flickr.jpg
./Images/subway/subway_0152.jpg
./Images/subway/subway_0146.jpg
./Images/subway/subway_0026.jpg
./Images/subway/subway_0032.jpg
./Images/subway/subway_0224.jpg
./Images/subway/subway_0230.jpg
./Images/subway/subway_0218.jpg
./Images/subway/subway_0226.jpg
./Images/subway/subway_0232.jpg
./Images/subway/subway_0018.jpg
./Images/subway/subway_0024.jpg
./Images/subway/subway_0030.jpg
./Images/subway/subway_0178.jpg
./Images/subway/subway_0150.jpg
./Images/subway/subway_0144.jpg
./Images/subway/subway_0193.jpg
./Images/subway/subwa

In [3]:
len(X)

15579

In [4]:
# Test X
X


        [145, 148, 143, ...,  52,  38,  33],
        ...,
        [ 28,  11,  32, ...,  14,  21,  27],
        [ 77,  52,  82, ...,  74,  73,  35],
        [144, 141, 155, ...,  31,  61,  76]], dtype=uint8),
 array([[ 89,  85,  84, ...,  95,  90,  86],
        [ 95,  99, 102, ..., 125, 118, 112],
        [ 98,  99, 107, ..., 119, 124, 119],
        ...,
        [ 54, 107,  91, ...,  36,  26, 107],
        [ 40,  46,  57, ...,  38,  19,  75],
        [ 64, 115, 114, ...,  17,  19,  45]], dtype=uint8),
 array([[62, 55, 49, ..., 12, 12, 11],
        [66, 62, 52, ..., 13, 12, 11],
        [71, 66, 53, ..., 12, 11, 11],
        ...,
        [18, 18, 45, ..., 17, 46,  5],
        [54, 47, 44, ..., 11, 10, 14],
        [57, 60, 60, ..., 10,  9, 10]], dtype=uint8),
 array([[58, 61, 68, ..., 62, 58, 64],
        [54, 58, 61, ..., 81, 30, 64],
        [58, 58, 61, ..., 36, 80, 27],
        ...,
        [92, 96, 99, ...,  1,  4,  6],
        [86, 92, 93, ..., 13, 28,  6],
        [88, 90, 97, ..

In [5]:
# Test y
y

['meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room',
 'meeting_room

In [6]:
data

[]

In [7]:
np.save('X.npy', X)
np.save('y.npy', y)
np.save('data.npy', data)